"""Closed-form SEW-Mimic retargeting for seven-DoF humanoid arms."""

from .solver import (
    DegenerateGeometryError,
    JointLimitError,
    Serial7DoF,
    SEWMimicError,
    align_axis,
    align_wrist_parallel,
    alignment_diagnostics,
    equivalent_angles_in_limits,
    make_frame,
    rot,
    sew_mimic,
    skew,
    sp1,
    sp2,
    sp4,
    unit,
    wrap_to_pi,
)

__all__ = [
    "DegenerateGeometryError",
    "JointLimitError",
    "SEWMimicError",
    "Serial7DoF",
    "align_axis",
    "align_wrist_parallel",
    "alignment_diagnostics",
    "equivalent_angles_in_limits",
    "make_frame",
    "rot",
    "sew_mimic",
    "skew",
    "sp1",
    "sp2",
    "sp4",
    "unit",
    "wrap_to_pi",
]
