"""Closed-form SEW-Mimic retargeting for seven-DoF humanoid arms."""

from .collision import (
    Capsule,
    CapsuleContact,
    capsule_contact,
    capsule_from_oobb,
    closest_points_on_segments,
)
from .safety import (
    ArmPose,
    BimanualPose,
    CapsuleIndex,
    CapsuleRadii,
    SafetyFilterConfig,
    SafetyFilterResult,
    SafetyFilterStatus,
    find_first_collision,
    minimum_capsule_distance,
    recover_tool_orientation,
    sew_safety_filter,
)
from .solver import (
    Serial7DoF,
    align_axis,
    align_wrist_parallel,
    alignment_diagnostics,
    sew_mimic,
    sp1,
    sp2,
    sp4,
)
from .utility import (
    DegenerateGeometryError,
    JointLimitError,
    SEWMimicError,
    as_vec3,
    configure_logging,
    equivalent_angles_in_limits,
    is_rotation_matrix,
    make_frame,
    rot,
    skew,
    unit,
    wrap_to_pi,
)

__all__ = [
    "ArmPose",
    "BimanualPose",
    "Capsule",
    "CapsuleContact",
    "CapsuleRadii",
    "CapsuleIndex",
    "DegenerateGeometryError",
    "JointLimitError",
    "SEWMimicError",
    "SafetyFilterConfig",
    "SafetyFilterResult",
    "SafetyFilterStatus",
    "Serial7DoF",
    "align_axis",
    "align_wrist_parallel",
    "alignment_diagnostics",
    "as_vec3",
    "capsule_contact",
    "capsule_from_oobb",
    "closest_points_on_segments",
    "configure_logging",
    "equivalent_angles_in_limits",
    "is_rotation_matrix",
    "find_first_collision",
    "make_frame",
    "minimum_capsule_distance",
    "recover_tool_orientation",
    "rot",
    "sew_mimic",
    "sew_safety_filter",
    "skew",
    "sp1",
    "sp2",
    "sp4",
    "unit",
    "wrap_to_pi",
]
